// Code generated by protoc-gen-echo. DO NOT EDIT.
// versions:
// - protoc-gen-echo 0.0.2
// - protoc          4.23.4
// source: example/example.proto

package example

import (
	v4 "github.com/labstack/echo/v4"
)

var _ = new(v4.Context)

type ExampleServiceEchoHandler interface {
	// Hello hello
	Hello(v4.Context) error
	// Say say
	Say(v4.Context) error
}
