// Code generated by protoc-gen-echo. DO NOT EDIT.
// versions:
// - protoc-gen-echo 0.0.3
// - protoc          4.23.4
// source: example/example.proto

package example

import (
	v4 "github.com/labstack/echo/v4"
)

var _ = new(v4.Context)

type ExampleServiceEchoHandler interface {
	// Hello hello
	Hello(v4.Context) error
	// Say say
	Say(v4.Context) error
}

// ExampleService_HelloBinder
func ExampleService_HelloBinder(c v4.Context) (*HelloRequest, error) {
	var args *HelloRequest
	if err := c.Bind(&args); err != nil {
		return &HelloRequest{}, err
	}
	return args, nil
}

// ExampleService_SayBinder
func ExampleService_SayBinder(c v4.Context) (*SayRequest, error) {
	var args *SayRequest
	if err := c.Bind(&args); err != nil {
		return &SayRequest{}, err
	}
	return args, nil
}
