// Code generated by protoc-gen-echo. DO NOT EDIT.
// versions:
// - protoc-gen-echo 0.0.7
// - protoc          0.0.0
// source: example.proto

package example

import (
	v4 "github.com/labstack/echo/v4"
	http "net/http"
)

var _ = new(v4.Context)
var _ = new(http.Client)

// type myHandler {
//     ExampleService_EchoClientHandlerImpl
//	   Log *slog.Logger
// }
//
// func NewMyHandler(log *slog.Logger) *myHandler {
// 	   return &myHandler{Log: log}
// }
//
// func main () {
//     e := echo.New()
//     log := slog.New(slog.NewJSONHandler(os.Stdout, &slog.HandlerOptions{}))
//     handler := example.NewExampleService_EchoServerHandler(NewMyHandler(log))
//     e.Get("/", e.handler.Hello)
//     if err := e.Start(":1111"); err != nil {
//         panic(err)
//     }
// }
//
// func (h myHandler) Hello(args *example.HelloRequest) (*example.HelloResponse, error) {
//     h.Log.Info("打印参数", slog.Any("args", args))
//     return &example.HelloResponse{Msg: args.Name}, nil
// }

type ExampleService_EchoServerHandler interface {
	// Hello hello
	Hello(v4.Context) error
	// Say say
	Say(v4.Context) error
}

type ExampleService_EchoServerHandlerImpl struct {
	Handler ExampleService_EchoClientHandler
}

func NewExampleService_EchoServerHandler(handler ExampleService_EchoClientHandler) ExampleService_EchoServerHandler {
	return &ExampleService_EchoServerHandlerImpl{
		Handler: handler,
	}
}

// Hello hello
func (s ExampleService_EchoServerHandlerImpl) Hello(c v4.Context) error {
	var args HelloRequest
	if err := c.Bind(&args); err != nil {
		return err
	}

	resp, err := s.Handler.Hello(&args)
	if err != nil {
		return err
	}

	return c.JSON(http.StatusOK, resp)
}

// Say say
func (s ExampleService_EchoServerHandlerImpl) Say(c v4.Context) error {
	var args SayRequest
	if err := c.Bind(&args); err != nil {
		return err
	}

	resp, err := s.Handler.Say(&args)
	if err != nil {
		return err
	}

	return c.JSON(http.StatusOK, resp)
}

type ExampleService_EchoClientHandler interface {
	// Hello hello
	Hello(*HelloRequest) (*HelloResponse, error)
	// Say say
	Say(*SayRequest) (*SayResponse, error)
}

type ExampleService_EchoClientHandlerImpl struct {
}

func NewExampleService_EchoClientHandler() ExampleService_EchoClientHandler {
	return &ExampleService_EchoClientHandlerImpl{}
}

// Hello hello 方法需要自己实现
func (ExampleService_EchoClientHandlerImpl) Hello(args *HelloRequest) (*HelloResponse, error) {
	return &HelloResponse{}, nil
}

// Say say 方法需要自己实现
func (ExampleService_EchoClientHandlerImpl) Say(args *SayRequest) (*SayResponse, error) {
	return &SayResponse{}, nil
}
